apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nginx-1"},"name":"nginx-1","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx-1"}},"template":{"metadata":{"labels":{"app":"nginx-1"}},"spec":{"containers":[{"image":"haaz77/hasnginx","name":"hasnginx"}]}}}}
    creationTimestamp: 2018-07-12T09:26:02Z
    generation: 2
    labels:
      app: nginx-1
    name: nginx-1
    namespace: default
    resourceVersion: "3307"
    selfLink: /apis/apps/v1/namespaces/default/deployments/nginx-1
    uid: 988f7fd2-85b5-11e8-a4fe-42010a800247
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: nginx-1
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nginx-1
      spec:
        containers:
        - image: haaz77/hasnginx
          imagePullPolicy: Always
          name: hasnginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2018-07-12T09:26:37Z
      lastUpdateTime: 2018-07-12T09:26:37Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: 2018-07-12T09:26:03Z
      lastUpdateTime: 2018-07-12T09:26:37Z
      message: ReplicaSet "nginx-1-66cbfc5788" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2018-07-12T09:26:03Z
    generation: 2
    labels:
      app: nginx-1
      pod-template-hash: "2276971344"
    name: nginx-1-66cbfc5788
    namespace: default
    ownerReferences:
    - apiVersion: extensions/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: nginx-1
      uid: 988f7fd2-85b5-11e8-a4fe-42010a800247
    resourceVersion: "3306"
    selfLink: /apis/apps/v1/namespaces/default/replicasets/nginx-1-66cbfc5788
    uid: 989278c9-85b5-11e8-a4fe-42010a800247
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: nginx-1
        pod-template-hash: "2276971344"
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nginx-1
          pod-template-hash: "2276971344"
      spec:
        containers:
        - image: haaz77/hasnginx
          imagePullPolicy: Always
          name: hasnginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2018-07-12T09:33:34Z","reason":"ReadyForNewScale","message":"the
        last scale time was sufficiently old as to warrant a new scale"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2018-07-12T09:28:33Z","reason":"ValidMetricFound","message":"the
        HPA was able to successfully calculate a replica count from cpu resource utilization
        (percentage of request)"},{"type":"ScalingLimited","status":"True","lastTransitionTime":"2018-07-12T09:28:33Z","reason":"TooFewReplicas","message":"the
        desired replica count is increasing faster than the maximum scale rate"}]'
      autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":0,"currentAverageValue":"0"}}]'
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"autoscaling/v1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"app":"nginx-1"},"name":"nginx-1-hpa","namespace":"default"},"spec":{"maxReplicas":5,"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1beta1","kind":"Deployment","name":"nginx-1"},"targetCPUUtilizationPercentage":80}}
    creationTimestamp: 2018-07-12T09:26:03Z
    labels:
      app: nginx-1
    name: nginx-1-hpa
    namespace: default
    resourceVersion: "3728"
    selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/nginx-1-hpa
    uid: 98aaefcb-85b5-11e8-a4fe-42010a800247
  spec:
    maxReplicas: 5
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1beta1
      kind: Deployment
      name: nginx-1
    targetCPUUtilizationPercentage: 80
  status:
    currentCPUUtilizationPercentage: 0
    currentReplicas: 1
    desiredReplicas: 1
    lastScaleTime: 2018-07-12T09:28:33Z
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
        hasnginx'
    creationTimestamp: 2018-07-12T09:26:03Z
    generateName: nginx-1-66cbfc5788-
    labels:
      app: nginx-1
      pod-template-hash: "2276971344"
    name: nginx-1-66cbfc5788-kxvf4
    namespace: default
    ownerReferences:
    - apiVersion: extensions/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: nginx-1-66cbfc5788
      uid: 989278c9-85b5-11e8-a4fe-42010a800247
    resourceVersion: "3131"
    selfLink: /api/v1/namespaces/default/pods/nginx-1-66cbfc5788-kxvf4
    uid: 989b3b32-85b5-11e8-a4fe-42010a800247
  spec:
    containers:
    - image: haaz77/hasnginx
      imagePullPolicy: Always
      name: hasnginx
      resources:
        requests:
          cpu: 100m
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-r2v9z
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-cluster-1-default-pool-71780170-qr29
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: default-token-r2v9z
      secret:
        defaultMode: 420
        secretName: default-token-r2v9z
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2018-07-12T09:26:03Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2018-07-12T09:26:36Z
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2018-07-12T09:26:03Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://11c90d55e5f1de62e62daeb99434ee270bbb06929f6c455ba3d5220dec15ad0a
      image: haaz77/hasnginx:latest
      imageID: docker-pullable://haaz77/hasnginx@sha256:545e5a5d98e2436c21ef7a2ae1a9de6771c5b0b3247468097b54c4ca712c429c
      lastState: {}
      name: hasnginx
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2018-07-12T09:26:36Z
    hostIP: 10.128.0.2
    phase: Running
    podIP: 10.8.2.7
    qosClass: Burstable
    startTime: 2018-07-12T09:26:03Z
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2018-07-12T08:54:55Z
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "6"
    selfLink: /api/v1/namespaces/default/services/kubernetes
    uid: 3f2c60aa-85b1-11e8-a4fe-42010a800247
  spec:
    clusterIP: 10.11.240.1
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    sessionAffinity: ClientIP
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
