apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nginx-1"},"name":"nginx-1","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx-1"}},"template":{"metadata":{"labels":{"app":"nginx-1"}},"spec":{"containers":[{"image":"haaz77/hasnginx","name":"hasnginx"}]}}}}
  creationTimestamp: 2018-07-12T09:26:02Z
  generation: 1
  labels:
    app: nginx-1
  name: nginx-1
  namespace: default
  resourceVersion: "3141"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nginx-1
  uid: 988f7fd2-85b5-11e8-a4fe-42010a800247
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-1
    spec:
      containers:
      - image: haaz77/hasnginx
        imagePullPolicy: Always
        name: hasnginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: 2018-07-12T09:26:37Z
    lastUpdateTime: 2018-07-12T09:26:37Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-07-12T09:26:03Z
    lastUpdateTime: 2018-07-12T09:26:37Z
    message: ReplicaSet "nginx-1-66cbfc5788" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3

